blank_issues_enabled: true
contact_links:
  - name: Documentation
    url: https://github.com/Robert-P-M/kmp_resources
    about: Check the README file in the first place.
  - name: Getting Help
    url: https://github.com/Robert-P-M/kmp_resources/issues
    about: Open an issue if you need help or found a bug.