package dev.robdoes.kmpresources.presentation.editor

import com.intellij.icons.AllIcons
import dev.robdoes.kmpresources.core.shared.LocaleInfo
import dev.robdoes.kmpresources.domain.model.PluralsResource
import dev.robdoes.kmpresources.domain.model.StringArrayResource
import dev.robdoes.kmpresources.domain.model.StringResource
import dev.robdoes.kmpresources.domain.model.XmlResource
import dev.robdoes.kmpresources.presentation.editor.model.ResourceColumn
import dev.robdoes.kmpresources.presentation.editor.model.ResourceStatus

/**
 * Object responsible for mapping XML-based resources ([XmlResource]) into structured rows
 * to be used in tabular representations, such as a visual resource management table.
 *
 * The rows generated by this mapper include metadata, default values, and localized values
 * for each resource, taking into account the presence of specific resource subtypes (e.g.,
 * strings, plurals, and string arrays).
 *
 * Functions:
 * @function mapToRows Maps an [XmlResource] into a list of rows, where each row is represented
 * as an array of values, based on the type of resource and its localization information.
 * The output rows include headers, metadata columns (e.g., status, key, type), and
 * columns for each provided locale's localized values.
 *
 * @param res The [XmlResource] to be mapped into rows.
 * @param locales A list of [LocaleInfo] objects, each representing a specific locale.
 * The localized values for each locale will be added as columns in the resulting rows.
 * @param loadingStatus Metadata indicating the loading or synchronization status of the resource.
 * This is used to populate the status column in the resulting rows.
 * @return A list of rows ([Array<Any?>]) representing the resource, its default values,
 * and its localized values for the specified locales.
 *
 * Internal Details:
 * - Handles different types of resources ([StringResource], [PluralsResource],
 *   [StringArrayResource]) and maps them accordingly.
 * - Generates sub-rows for complex resource types (e.g., plural quantities, string array items).
 * - Accounts for metadata such as resource type, translatability, and deletion options
 *   in the resulting rows.
 * - Computes and aligns the number of localized entries for complex types, ensuring
 *   consistency across provided locales.
 *
 * Note:
 * This object assumes that the provided [XmlResource] and [LocaleInfo] inputs
 * adhere to the expected structures and property specifications.
 */
internal object ResourceRowMapper {

    /**
     * Maps an XML resource into a list of rows, each represented as an array of values,
     * based on the resource type (e.g., string, plurals, or string array) and provided locale information.
     * These rows are used to display and manipulate localization data for the resource.
     *
     * @param res The XML resource to be mapped. This resource can be of type StringResource,
     *            PluralsResource, or StringArrayResource.
     * @param locales The list of locales to be included in the rows. Each locale represents
     *                a language or region configuration.
     * @param loadingStatus Metadata representing the current resource status, typically used
     *                      for display purposes (e.g., status icons or tooltips).
     * @return A list of rows, where each row is an array of values representing the resource properties,
     *         translations, and related metadata. The number and structure of rows vary
     *         depending on the resource type.
     */
    fun mapToRows(
        res: XmlResource,
        locales: List<LocaleInfo>,
        loadingStatus: ResourceStatus
    ): List<Array<Any?>> {
        val rows = mutableListOf<Array<Any?>>()

        when (res) {
            is StringResource -> {
                rows.add(createBaseRow(res, res.key, res.type.xmlTag, res.isUntranslatable, locales, loadingStatus))
            }

            is PluralsResource -> {
                rows.add(createBaseRow(res, res.key, res.type.xmlTag, res.isUntranslatable, locales, loadingStatus))
                res.type.supportedQuantities.forEach { q ->
                    val subRow = createBaseRow(res, "", q, false, locales, loadingStatus, quantity = q)
                    subRow[ResourceColumn.USAGE.index] = null
                    rows.add(subRow)
                }
            }

            is StringArrayResource -> {
                rows.add(createBaseRow(res, res.key, res.type.xmlTag, res.isUntranslatable, locales, loadingStatus))

                val defaultSize = res.localizedItems[null]?.size ?: 0
                val maxItems = locales.maxOfOrNull { res.localizedItems[it.languageTag]?.size ?: 0 } ?: 0
                val finalMax = maxOf(maxItems, defaultSize)

                for (i in 0 until finalMax) {
                    val subRow = createBaseRow(res, "", "item[$i]", false, locales, loadingStatus, index = i)
                    subRow[ResourceColumn.USAGE.index] = null
                    rows.add(subRow)
                }
                rows.add(createBaseRow(res, "", "item[+]", false, locales, loadingStatus).apply {
                    this[ResourceColumn.DELETE.index] = null
                })
            }
        }
        return rows
    }

    /**
     * Creates and initializes a base row for a resource table representation.
     *
     * This method constructs an array to represent a single row in the resource table.
     * The row contains metadata about the resource, localized values for each specified locale,
     * and additional attributes such as type, status, and translatability. The structure
     * accommodates the required columns and dynamically appends columns for locale-specific values.
     *
     * @param res The XML resource used to retrieve resource values and metadata.
     * @param key The unique identifier for the resource.
     * @param type The type of the resource (e.g., string, plurals, string-array).
     * @param isUn A flag indicating whether the resource is untranslatable.
     * @param locales A list of locales for which resource values are retrieved.
     * @param status The metadata representing the status of the resource.
     * @param quantity (Optional) The quantity for retrieving pluralized resource values.
     * @param index (Optional) The index for retrieving array-based resource values.
     * @return An array representing the constructed row, with columns for metadata and locale-specific values.
     */
    private fun createBaseRow(
        res: XmlResource,
        key: String,
        type: String,
        isUn: Boolean,
        locales: List<LocaleInfo>,
        status: ResourceStatus,
        quantity: String? = null,
        index: Int? = null
    ): Array<Any?> {
        val row = arrayOfNulls<Any?>(ResourceColumn.entries.size + locales.size)
        row[ResourceColumn.STATUS.index] = status
        row[ResourceColumn.KEY.index] = key
        row[ResourceColumn.USAGE.index] = if (key.isNotEmpty()) AllIcons.Actions.Search else null
        row[ResourceColumn.DELETE.index] = AllIcons.General.Remove
        row[ResourceColumn.UNTRANSLATABLE.index] = isUn
        row[ResourceColumn.TYPE.index] = type

        row[ResourceColumn.DEFAULT_VALUE.index] = getValue(res, null, quantity, index)

        locales.forEachIndexed { i, locale ->
            val colIdx = ResourceColumn.entries.size + i
            row[colIdx] = getValue(res, locale.languageTag, quantity, index)
        }

        return row
    }

    /**
     * Retrieves a localized resource value based on the provided resource, locale, quantity, and index.
     *
     * This function supports multiple resource types including [StringResource], [PluralsResource], and [StringArrayResource].
     * It fetches the appropriate value depending on the resource type and the given parameters.
     *
     * @param resource An instance of [XmlResource] representing the resource to retrieve the value from.
     *                 It can be a string, plural, or string array resource.
     * @param localeTag The locale tag (e.g., "en", "fr") to fetch the localized value. If `null`, it fetches the default value.
     * @param quantity For plural resources ([PluralsResource]), this specifies the quantity category (e.g., "one", "few").
     *                 It is ignored for non-plural resource types.
     * @param index For string array resources ([StringArrayResource]), this specifies the index of the array element to retrieve.
     *              If `null` or out of bounds, an empty string is returned. This parameter is ignored for other resource types.
     * @return A localized string value based on the input parameters. If no value is found, an empty string is returned.
     */
    private fun getValue(resource: XmlResource, localeTag: String?, quantity: String?, index: Int?): String {
        return when (resource) {
            is StringResource -> resource.values[localeTag] ?: ""
            is PluralsResource -> resource.localizedItems[localeTag]?.get(quantity ?: "") ?: ""
            is StringArrayResource -> {
                val items = resource.localizedItems[localeTag] ?: emptyList()
                if (index != null && index in items.indices) items[index] else ""
            }
        }
    }
}